### ISSUE TITLE
ERROR#132

### ISSUE THREAD

**Issue by kokpk** [hannesmann/vanillafixes#57] opened 2024-08-31 12:07 UTC
vanillafixes-1.4.1-dxvk Windowed Mode
![1725105906044](https://github.com/user-attachments/assets/b0192696-7892-4d0f-b07e-6eb11ddc0f47)

**Comment by jcockream** [comment] 2024-09-05 20:37
Are you also using AutoLogin? I was having this same issue when I used AutoLogin, removed it, and the crashing went away.

**Comment by kokpk** [comment] 2024-09-08 18:14
> Are you also using AutoLogin? I was having this same issue when I used AutoLogin, removed it, and the crashing went away.

no~

**Comment by hannesmann** [comment] 2024-09-13 02:36
This is almost always caused by DXVK (a dialog like [this](https://raw.githubusercontent.com/hannesmann/vanillafixes/v1.4/docs/messagebox-dxvk-selftest.png) should show up). Try removing d3d9.dll to use VanillaFixes without DXVK. If it still doesn't work, it's caused by some other mod you have installed.

**Comment by Luccifer** [comment] 2024-09-16 12:50
I deleted the dll for manymonitors from dll.txt and also used  73 KB exe download

**Comment by hannesmann** [comment] 2024-10-04 16:06
Closing since this doesn't seem to be related to VanillaFixes.

**Closed by hannesmann** 2024-10-04 16:06 UTC
