### ISSUE TITLE
the mouse becomes smaller

### ISSUE THREAD

**Issue by pengzou123** [hannesmann/vanillafixes#37] opened 2023-11-02 11:53 UTC
After installation, run the game and the mouse becomes smaller. What's going on?

**Comment by hannesmann** [comment] 2023-11-06 19:05
Probably caused by DXVK.
https://github.com/doitsujin/dxvk/blob/master/dxvk.conf#L384

Try adding `d3d9.dpiAware = False` to dxvk.conf.

**Comment by shikulja** [comment] 2023-11-07 03:35
its helps for me in 4k

**Comment by pengzou123** [comment] 2023-11-07 04:39
Thank you for your reply. After modification, re-entering the game, you need to turn off the hardware mouse in the settings to restore the mouse to normal. But turning off dpi scaling will make the font blur.

**Comment by hannesmann** [comment] 2024-04-24 00:40
Closing since the question has been answered (v1.4 will always disable DPI scaling).

**Closed by hannesmann** 2024-04-24 00:40 UTC
