### ISSUE TITLE
Screen blinks or flickers

### ISSUE THREAD

**Issue by jtkimbell** [hannesmann/vanillafixes#13] opened 2023-05-04 06:29 UTC
I installed this via the instructions here: https://turtle-wow.fandom.com/wiki/Client_Fixes_and_Tweaks

I Installed the DXVK version as I have a GTX 1660 Super. Unfortunately the screen would go black for a fraction of a second every 30 seconds or so. I deleted all the files and the issue no longer persists.

Let me know if I can get a video or anything else to help.

**Comment by hannesmann** [comment] 2023-05-07 01:36
Does it still happen if you use the version without DXVK (vanillafixes-1.2.zip)? VanillaFixes by itself doesn't modify anything related to the rendering of the game so it's probably DXVK causing issues.

**Comment by jtkimbell** [comment] 2023-05-07 02:12
Good suggestion, I will try that, thank you!
JT

    On Saturday, May 6, 2023 at 06:37:07 PM PDT, Hannes Mann ***@***.***> wrote:  
 
 


Does it still happen if you use the version without DXVK (vanillafixes-1.2.zip)? VanillaFixes by itself doesn't modify anything related to the rendering of the game so it's probably DXVK causing issues.

**Comment by NinaFelwitch** [comment] 2023-06-02 16:25
I can confirm this behaviour. 
With the d3d9.dll in the folder, I have two issues. 
The game is locked at 60fps and I get a flickering screen on dual monitor setup when I alt-tab out of the game.
To be specific, the flickering occurs when a window on the second screen moves close to the screen where the game is running. This is quite weird, because the window is not actually touching the first screen, only getting close. But this causes massive flickering on the first screen where the game is being displayed.

The solution is to either force a refresh of the graphics driver, for example by turning the screen off and on again, or by changing freesync settings (disabling freesync itself doesn't solve the issue). 
Or by deleting the d3d9.dll. 
My fps returns to the screen refresh rate (144)(outside of cities- right now I have between 95 and 105 in Orgrimmar with Vanilla Tweaks on default settings) and the flickering stops.

My specs:
Windows 10, AMD Radeon RX 6800 XT, Intel i5-12600KF, drivers all up to date.

**Comment by hannesmann** [comment] 2024-04-24 00:43
Closing since this is an issue with DXVK and not VanillaFixes.

**Closed by hannesmann** 2024-04-24 00:43 UTC
