### ISSUE TITLE
Second Windows screen flickers/black screen 

### ISSUE THREAD

**Issue by Morons** [hannesmann/vanillafixes#50] opened 2024-06-29 09:22 UTC
I have a duel screen set-up

I find using Vinilla (Either versions) cause the window second screen to go black and then re-initialise after a while each time I switch my focus (click) on the second screen and again switching back to the Maxed-Windowed client.

I use the second screen for QOL such as wiki etc.

**Comment by hannesmann** [comment] 2024-06-29 19:53
This sounds like a duplicate of #36. Try removing DXVK (d3d9.dll) and see if that changes anything.

**Comment by Morons** [comment] 2024-06-30 08:54
> This sounds like a duplicate of #36. Try removing DXVK (d3d9.dll) and see if that changes anything.

Fixed Thanx for the tip

**Closed** 2024-06-30 10:48 UTC
