### ISSUE TITLE
How to use it w/ wowreeb launcher?

### ISSUE THREAD

**Issue by laytya** [hannesmann/vanillafixes#3] opened 2022-12-25 09:38 UTC
Could not make it work.
example?

**Comment by hannesmann** [comment] 2022-12-26 20:49
Looking at the example config (https://github.com/namreeb/wowreeb/blob/master/example_config.xml#L34) it seems like there's an issue with the way wowreeb loads DLLs: It requires an exported method to call in the DLL. VanillaFixes doesn't work this way, instead relying on `DLL_PROCESS_ATTACH` and `DLL_PROCESS_DETACH` to modify game code.

I could make a workaround in VanillaFixes by adding an empty placeholder function for wowreeb to call but there's another issue, it only supports loading one DLL per instance. This means VanillaFixes and nampower wouldn't work together if you use wowreeb.

I opened an issue here: https://github.com/namreeb/wowreeb/issues/20. I won't be home until next week but if the issue isn't resolved by then I'll fix it myself and open a pull request for wowreeb.

**Comment by laytya** [comment] 2022-12-27 09:38
I m personally dont use nampower, so u can make fix for VanillaFixes  to test it work

**Comment by hannesmann** [comment] 2022-12-27 17:11
OK, I haven't tested this but it should work: 
https://github.com/hannesmann/vanillafixes/blob/wowreeb-workaround/bin/VfPatcher.dll?raw=true

Load with `<DLL Path="VfPatcher.dll" Method="Load" />`.

**Comment by laytya** [comment] 2022-12-28 02:19
Its starts now. Thanx

**Comment by hannesmann** [comment] 2022-12-29 00:41
Issue has been fixed in wowreeb 3.5.

**Closed by hannesmann** 2022-12-29 00:41 UTC
