### ISSUE TITLE
Feature: AutoLogin compatibility

### ISSUE THREAD

**Issue by Zebouski** [hannesmann/vanillafixes#1] opened 2022-12-21 21:07 UTC
I multibox on vanilla a lot and also have access to about 15 accounts via alts and friends'. https://github.com/Caraxi/AutoLogin is crucial to be able to log in with a bunch of different creds easily. Does it look like this and that can be made both usable at once, so that I can continue using scripts that open multiple game windows with multiple creds auto-typed in?

**Comment by hannesmann** [comment] 2022-12-21 21:27
That looks like a tool for Final Fantasy XIV? I don't really understand how it works. 

If you need to change what executable the auto login tool launches, that should be changed in the auto login tool (from WoW.exe to VanillaFixes.exe).

If you need to inject a DLL, that can be added here: https://github.com/hannesmann/vanillafixes/blob/main/src/launcher.c#L93 (but it would probably be easier to use another more flexible launcher like wowreeb)

**Comment by Zebouski** [comment] 2022-12-21 22:09
Sorry wrong link lol
https://github.com/EinBaum/AutoLogin

Good thought, I gave this a try
`./AutoLogin/bin/AutoLogin.exe VanillaFixes.exe Username Password 1000`
The game launches with your tool's effects in work, but yeah nah the auto-typing doesn't work, nothing is entered

Looking at its code, it looks pretty simple if ya would just like to add its functionality to your program, though i understand if that is scope bloat.

But yeah thanks for looking into this to make this more usable for my workflow. This tool is dope and I'm absolutely noticing the difference it makes.

**Comment by hannesmann** [comment] 2022-12-21 23:08
I see what the issue is: AutoLogin is waiting for VanillaFixes.exe to create a window, not WoW.exe. It wouldn't work the other way around either because VanillaFixes expects to be able to inject into the process that it creates.

I'm not going to add this functionality to VanillaFixes but AutoLogin was indeed pretty simple so I created a quick fix for it. Could you try this and see if it works?
https://github.com/hannesmann/AutoLogin/blob/master/bin/AutoLogin.exe?raw=true

**Comment by Zebouski** [comment] 2022-12-22 09:42
You're a saint for taking a look at that other project and trying to get it working, big thanks man

Unfortunately no, your forked exe still doesn't work for me, but looking into it this might now be a wine bug on my linux install, I've seen similarly before where wine processes have difficulty finding other wine processes. I don't have a windows vm up anymore for me to test with either. If it did work for you, then I think you've done everything your side you can and i'll have to figure out a different solution for my logins, or figure out if anything can be done about wine here

**Comment by hannesmann** [comment] 2022-12-22 22:43
> You're a saint for taking a look at that other project and trying to get it working, big thanks man

No problem, it was a really easy fix :) 

> Unfortunately no, your forked exe still doesn't work for me, but looking into it this might now be a wine bug on my linux install, I've seen similarly before where wine processes have difficulty finding other wine processes

I actually tested it in Wine and it seemed to work for me. It enters the username and password I select if I launch the game with `wine AutoLogin.exe VanillaFixes.exe Username Password 1000` (but it doesn't automatically click the login button). 

Like I said I'm not going to add this functionality to VanillaFixes. Convenience features have already been done by other projects before and I want to keep this a simple fix for a problem with the 1.12 engine. I'll close this issue since this should be fixed in the auto login tool.

**Closed by hannesmann** 2022-12-22 22:43 UTC

**Comment by Zebouski** [comment] 2022-12-28 18:46
I got it working now. This is HUGE! thank you so much man
