### ISSUE TITLE
Scrollwheel up/down not working

### ISSUE THREAD

**Issue by thom4466** [hannesmann/vanillafixes#38] opened 2023-11-10 23:11 UTC
I installed it on TurtleWoW and suddenly I couldnt use scrollwheel as in the game doesnt even register the action anymore, cant rebind it either.
Scrollwheel works fine if I just use the wow.exe instead so its only happening with vanillafixes.
Will gladly show on discord if it will help solve this problem.

**Comment by journeym** [comment] 2024-01-16 20:48
using on turtle wow, scroll wheel is working

**Comment by hannesmann** [comment] 2024-09-13 02:42
Closing since this doesn't seem to be caused by VanillaFixes and there haven't been any more reports of this problem

**Closed by hannesmann** 2024-09-13 02:42 UTC
