### ISSUE TITLE
Player character and NPCs randomly vanishing while in-doors on TurtleWoW 1.17 with VanillaFixes

### ISSUE THREAD

**Issue by skadigladi** [hannesmann/vanillafixes#34] opened 2023-10-19 10:07 UTC
As the title says, my character very often vanish and then re-appear when walking in-doors or inside dungeons, like it's being culled or failing to render, and this happens sometimes, but not as often, to other player models or NPCs in the same situations.

**Comment by hannesmann** [comment] 2023-10-20 10:14
Duplicate of #21

**Closed by hannesmann** 2023-10-20 10:14 UTC
