### ISSUE TITLE
Huge lag & FPS Spikes & Freezes.  AMD system

### ISSUE THREAD

**Issue by Josephienvandermeersch** [hannesmann/vanillafixes#48] opened 2024-05-04 14:15 UTC
Hello, I've used Fixes before on my laptop and other pcs and it worked perfectly but on my new system wich has AMD AM5 & 6950 XT GPU i'm having major issues with it, tried older versions as well, tried clean install, no addons, removed tweaks just fixes, but nothing.

Huge lag
Huge Freezes
Spiking my fps from 20-160 constantly
Disabled anti virus
Disabled any blocking
Admin runned it 
Put it on exclusions lists of anti virus

**Comment by hannesmann** [comment] 2024-05-08 20:57
I also have an AMD system (5800X / 6700 XT) so that shouldn't be an issue. Maybe you don't have Vulkan installed, make sure you install the latest drivers from AMD (not Windows Update): https://www.amd.com/en/support/download/drivers.html

**Comment by gojiguy28** [comment] 2024-08-15 05:15
Worked for weeks now all of a sudden freezing amd 5700x3d with up to date drivers.

**Comment by hannesmann** [comment] 2024-09-13 02:39
Closing since this doesn't seem to be caused by VanillaFixes

**Closed by hannesmann** 2024-09-13 02:39 UTC
